### ISSUE TITLE
Output transfer function for VTK.js consumption

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itk-viewer-transfer-function-editor#7]
- [ ] VTK.js volume renderer example with TfEditor
- [ ] Add utility function converting TfEditor Points to VTK.js transfer function

**Comment by thewtex** [comment]
Similiar to :

https://github.com/Kitware/itk-vtk-viewer/blob/master/src/Context/ImageActorContext.js#L47-L57
